### ISSUE TITLE
Blogpost link returns 404

### ISSUE THREAD

**Issue by intltechventures** [mstechly/vqf#2]
The link in the README, referenced by "if you're unfamiliar with it you might find my blogpost about QAOA helpful." - returns a 404 for this link:
https://github.com/mstechly/vqf/blob/master/www.mustythoughts.com/Quantum-Approximate-Optimization-Algorithm-Explained.html

**Comment by intltechventures** [comment]
Michał  provided this link in our LinkedIn exchange today:

Quantum Approximate Optimization Algorithm explained
https://www.mustythoughts.com/quantum-approximate-optimization-algorithm-explained

**Comment by mstechly** [comment]
Thanks for spotting this!
Sorry it took me so long, I didn't get any notification from GitHub.
